name: Validate

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  flake:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45

    steps:
      - name: Repository checkout
        uses: actions/checkout@v7

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22

      - name: Validate configuration
        run: nix flake check --print-build-logs
